
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;






/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kitai-sama
 */
public class mahoa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mahoa.class.getName());

    /**
     * Creates new form mahoa
     */ 
    public mahoa() {
        initComponents();
           setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jpTieuDe = new javax.swing.JLabel();
        jpUser1 = new javax.swing.JPanel();
        btnDecryptUser1 = new javax.swing.JButton();
        btnEncryptUser1 = new javax.swing.JButton();
        txtOutputUser1 = new javax.swing.JTextField();
        txtMessUser1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpKey = new javax.swing.JPanel();
        txtKey = new javax.swing.JTextField();
        txtframe = new javax.swing.JTextField();
        btnGenerateKey = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpUser2 = new javax.swing.JPanel();
        btnEncryptUser2 = new javax.swing.JButton();
        btnDecryptUser2 = new javax.swing.JButton();
        txtOutputUser2 = new javax.swing.JTextField();
        txtMessUser2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jpUser3 = new javax.swing.JPanel();
        btnDecryptUser3 = new javax.swing.JButton();
        btnEncryptUser3 = new javax.swing.JButton();
        jpKey1 = new javax.swing.JPanel();
        txtKey1 = new javax.swing.JTextField();
        txtframe1 = new javax.swing.JTextField();
        btnGenerateKey1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jpTieuDe.setText("A5/1 Stream Cipher Văn Bản");

        jpUser1.setName(""); // NOI18N

        btnDecryptUser1.setText("Decrypt");
        btnDecryptUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptUser1ActionPerformed(evt);
            }
        });

        btnEncryptUser1.setText("Encrypt");
        btnEncryptUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptUser1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Output");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("User 1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Enter The Message:");

        javax.swing.GroupLayout jpUser1Layout = new javax.swing.GroupLayout(jpUser1);
        jpUser1.setLayout(jpUser1Layout);
        jpUser1Layout.setHorizontalGroup(
            jpUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUser1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUser1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnEncryptUser1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecryptUser1))
                    .addGroup(jpUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMessUser1)
                        .addComponent(txtOutputUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUser1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUser1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jpUser1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpUser1Layout.setVerticalGroup(
            jpUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtMessUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecryptUser1)
                    .addComponent(btnEncryptUser1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutputUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        btnGenerateKey.setText("GenerateKey");
        btnGenerateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKeyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Vui Lòng Nhập Key:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Frame:");

        javax.swing.GroupLayout jpKeyLayout = new javax.swing.GroupLayout(jpKey);
        jpKey.setLayout(jpKeyLayout);
        jpKeyLayout.setHorizontalGroup(
            jpKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKeyLayout.createSequentialGroup()
                .addGroup(jpKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKeyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKey)
                            .addComponent(txtframe)))
                    .addGroup(jpKeyLayout.createSequentialGroup()
                        .addGroup(jpKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpKeyLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnGenerateKey))
                            .addGroup(jpKeyLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKeyLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(45, 45, 45))
        );
        jpKeyLayout.setVerticalGroup(
            jpKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKeyLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtframe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerateKey)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEncryptUser2.setText("Encrypt");
        btnEncryptUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptUser2ActionPerformed(evt);
            }
        });

        btnDecryptUser2.setText("Decrypt");
        btnDecryptUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptUser2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Enter The Message:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("User 2");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Output");

        javax.swing.GroupLayout jpUser2Layout = new javax.swing.GroupLayout(jpUser2);
        jpUser2.setLayout(jpUser2Layout);
        jpUser2Layout.setHorizontalGroup(
            jpUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUser2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jpUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUser2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnEncryptUser2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecryptUser2))
                    .addGroup(jpUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMessUser2)
                        .addComponent(txtOutputUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUser2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUser2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel9))
                    .addGroup(jpUser2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)))
                .addGap(38, 38, 38))
        );
        jpUser2Layout.setVerticalGroup(
            jpUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUser2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtMessUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecryptUser2)
                    .addComponent(btnEncryptUser2))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutputUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jpTieuDe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jpTieuDe)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpUser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SP A5/1 Text", jPanel4);

        jpUser3.setName(""); // NOI18N

        btnDecryptUser3.setText("Decrypt");
        btnDecryptUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptUser3ActionPerformed(evt);
            }
        });

        btnEncryptUser3.setText("Encrypt");
        btnEncryptUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptUser3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUser3Layout = new javax.swing.GroupLayout(jpUser3);
        jpUser3.setLayout(jpUser3Layout);
        jpUser3Layout.setHorizontalGroup(
            jpUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUser3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jpUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEncryptUser3)
                    .addComponent(btnDecryptUser3))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jpUser3Layout.setVerticalGroup(
            jpUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUser3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnEncryptUser3)
                .addGap(18, 18, 18)
                .addComponent(btnDecryptUser3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerateKey1.setText("GenerateKey");
        btnGenerateKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKey1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vui Lòng Nhập Key:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Frame:");

        javax.swing.GroupLayout jpKey1Layout = new javax.swing.GroupLayout(jpKey1);
        jpKey1.setLayout(jpKey1Layout);
        jpKey1Layout.setHorizontalGroup(
            jpKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKey1Layout.createSequentialGroup()
                .addGroup(jpKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKey1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKey1)
                            .addComponent(txtframe1)))
                    .addGroup(jpKey1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKey1Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(jpKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKey1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKey1Layout.createSequentialGroup()
                        .addComponent(btnGenerateKey1)
                        .addGap(60, 60, 60))))
        );
        jpKey1Layout.setVerticalGroup(
            jpKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKey1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtframe1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerateKey1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("A5/1 Stream Cipher File-Hình Ảnh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jpKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jpUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpKey1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SP A5/1 File-Pic", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecryptUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptUser2ActionPerformed
        try {
            String encryptedMessage = txtMessUser2.getText(); // Lấy từ input của User2
            long combinedKey = generateCombinedKey(); // Sử dụng cùng hàm tạo khóa

            if (encryptedMessage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tin nhắn để giải mã.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StringBuilder decryptedMessage = new StringBuilder();
            for (char c : encryptedMessage.toCharArray()) {
                decryptedMessage.append((char) (c ^ (combinedKey & 0xFF)));
                combinedKey = combinedKey >> 8;
            }
            txtOutputUser2.setText(decryptedMessage.toString()); // Đặt vào output của User2
            System.out.println("Tin nhắn mã hóa (User2): " + encryptedMessage);
            System.out.println("Tin nhắn giải mã (User2): " + decryptedMessage.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi giải mã: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDecryptUser2ActionPerformed

    private void btnEncryptUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptUser2ActionPerformed
        try {
            String originalMessage = txtMessUser2.getText(); // Lấy từ input của User2
            long combinedKey = generateCombinedKey(); // Sử dụng cùng hàm tạo khóa

            if (originalMessage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tin nhắn để mã hóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StringBuilder encryptedMessage = new StringBuilder();
            for (char c : originalMessage.toCharArray()) {
                encryptedMessage.append((char) (c ^ (combinedKey & 0xFF)));
                combinedKey = combinedKey >> 8;
            }
            txtOutputUser2.setText(encryptedMessage.toString()); // Đặt vào output của User2
            System.out.println("Tin nhắn gốc (User2): " + originalMessage);
            System.out.println("Tin nhắn mã hóa (User2): " + encryptedMessage.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi mã hóa: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEncryptUser2ActionPerformed

//GEN-FIRST:event_btnGenerateKeyActionPerformed
        // Hàm trợ giúp để tạo khóa duy nhất từ khóa chia sẻ và số khung
private long generateCombinedKey() throws NumberFormatException {
    // 1. Lấy và làm sạch đầu vào
    String sharedKeyStr = txtKey.getText().trim();
    String frameNumberStr = txtframe.getText().trim();

    // 2. Kiểm tra trống
    if (sharedKeyStr.isEmpty() || frameNumberStr.isEmpty()) {
        throw new NumberFormatException("Khóa chia sẻ và/hoặc số khung không được để trống.");
    }
    
    // 3. Loại bỏ "0x" (nếu có)
    if (frameNumberStr.toLowerCase().startsWith("0x")) {
        frameNumberStr = frameNumberStr.substring(2);
    }

    try {
        // 4. Chuyển đổi
        long sharedKeyValue = sharedKeyStr.hashCode();
        long frameNumberValue = Long.parseLong(frameNumberStr, 16);

        // 5. Kết hợp và ĐẢM BẢO KHÔNG BẰNG 0
        long combinedKey = sharedKeyValue ^ frameNumberValue;
        
        // Nếu kết quả bằng 0, ta thay đổi nó thành một giá trị mặc định.
        if (combinedKey == 0) {
            return 0xDEADBEEFCAFEBABEL; // Một giá trị ngẫu nhiên, lớn và không bằng 0
        }
        
        return combinedKey;

    } catch (NumberFormatException e) {
        throw new NumberFormatException("Số khung '" + txtframe.getText() + "' không phải là một số hexa hợp lệ.");
    }
}

    private void btnGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Random random = new Random();
        int frameNumberInt = random.nextInt() & ((1 << 22) - 1);
        String frameNumberHex = String.format("%06X", frameNumberInt);
        txtframe.setText(frameNumberHex); 
        System.out.println("Số khung 22-bit ngẫu nhiên được tạo: " + frameNumberHex);
    }    
    
    
//GEN-LAST:event_btnGenerateKeyActionPerformed

    private void btnEncryptUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptUser1ActionPerformed
        try {
            String originalMessage = txtMessUser1.getText();
            long combinedKey = generateCombinedKey();

            if (originalMessage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tin nhắn để mã hóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StringBuilder encryptedMessage = new StringBuilder();
            for (char c : originalMessage.toCharArray()) {
                // Mã hóa từng ký tự bằng XOR với một phần của khóa
                // (combinedKey + i) để mỗi ký tự dùng một phần khóa khác nhau
                encryptedMessage.append((char) (c ^ (combinedKey & 0xFF)));
                combinedKey = combinedKey >> 8; // Thay đổi khóa một chút cho ký tự tiếp theo
            }
            txtOutputUser1.setText(encryptedMessage.toString());
            System.out.println("Tin nhắn gốc (User1): " + originalMessage);
            System.out.println("Tin nhắn mã hóa (User1): " + encryptedMessage.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi mã hóa: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEncryptUser1ActionPerformed

    private void btnDecryptUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptUser1ActionPerformed
        try {
            String encryptedMessage = txtMessUser1.getText(); // Lấy tin nhắn đã mã hóa từ input của User1
            long combinedKey = generateCombinedKey(); // Lấy lại khóa đã dùng để mã hóa

            if (encryptedMessage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tin nhắn để giải mã.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            StringBuilder decryptedMessage = new StringBuilder();
            for (char c : encryptedMessage.toCharArray()) {
                // Giải mã từng ký tự bằng XOR với cùng một phần của khóa
                // Thuật toán XOR là đối xứng: A XOR K = B => B XOR K = A
                decryptedMessage.append((char) (c ^ (combinedKey & 0xFF)));
                combinedKey = combinedKey >> 8; // Di chuyển khóa giống như khi mã hóa
            }
            txtOutputUser1.setText(decryptedMessage.toString());
            System.out.println("Tin nhắn mã hóa (User1): " + encryptedMessage);
            System.out.println("Tin nhắn giải mã (User1): " + decryptedMessage.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi giải mã: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
    }//GEN-LAST:event_btnDecryptUser1ActionPerformed
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
private void processFileWithStreamCipher(String inputFilePath, String outputFilePath) throws Exception {
    long combinedKey = generateCombinedKey(); // Lấy khóa đã được đảm bảo khác 0

    // Sử dụng try-with-resources để đảm bảo file luôn được đóng đúng cách
    try (FileInputStream fis = new FileInputStream(inputFilePath);
         FileOutputStream fos = new FileOutputStream(outputFilePath)) {

        byte[] buffer = new byte[8192]; // Tăng kích thước buffer để cải thiện hiệu năng
        int bytesRead;
        long currentKeySegment = combinedKey; // Khởi tạo luồng khóa

        // Các hằng số nguyên tố lớn để tạo luồng khóa giả ngẫu nhiên
        final long MULTIPLIER = 0x5DEECE66DL;
        final long ADDEND = 0xBL;
        final long MASK = (1L << 48) - 1;

        while ((bytesRead = fis.read(buffer)) != -1) {
            for (int i = 0; i < bytesRead; i++) {
                // XOR từng byte với một byte từ luồng khóa
                buffer[i] = (byte) (buffer[i] ^ (currentKeySegment & 0xFF));
                
                // CẬP NHẬT LUỒNG KHÓA (LOGIC MỚI)
                // Sử dụng công thức của một bộ sinh số giả ngẫu nhiên (LCG)
                // để đảm bảo luồng khóa luôn thay đổi và không thể đoán trước một cách dễ dàng.
                currentKeySegment = (currentKeySegment * MULTIPLIER + ADDEND) & MASK;
            }
            fos.write(buffer, 0, bytesRead);
        }
    }
}

    
    // Hàm xử lý sự kiện cho nút "Giải mã File"  
    private void btnDecryptUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptUser3ActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Chọn File hoặc Thư mục đã Mã hóa để Giải mã");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

    if (fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        // Người dùng đã hủy
        return; 
    }
    
    File selectedInput = fileChooser.getSelectedFile();
    
    JFileChooser outputChooser = new JFileChooser();
    outputChooser.setDialogTitle("Chọn Thư mục để Lưu Kết quả Giải mã");
    outputChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    
    if (outputChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
        // Người dùng đã hủy
        return; 
    }
    
    File selectedOutputLocation = outputChooser.getSelectedFile();

    try {
        if (selectedInput.isFile()) {
            // XỬ LÝ GIẢI MÃ TỆP
            String fileName = selectedInput.getName();
            int dotIndex = fileName.lastIndexOf('.');
            String baseName = (dotIndex == -1) ? fileName : fileName.substring(0, dotIndex);
            String extension = (dotIndex == -1) ? "" : fileName.substring(dotIndex);
            String decryptedFileName = baseName + " (Decrypted)" + extension;
            
            String outputFilePath = new File(selectedOutputLocation, decryptedFileName).getAbsolutePath();
            processFileWithStreamCipher(selectedInput.getAbsolutePath(), outputFilePath);
            
            // THÔNG BÁO THÀNH CÔNG
            JOptionPane.showMessageDialog(this, 
                "Tệp đã được giải mã thành công!\n\nĐã lưu tại:\n" + outputFilePath, 
                "Hoàn thành", 
                JOptionPane.INFORMATION_MESSAGE);

        } else if (selectedInput.isDirectory()) {
            // XỬ LÝ GIẢI MÃ THƯ MỤC
            String outputDirPath = new File(selectedOutputLocation, selectedInput.getName().replace(" (Encrypted)", " (Decrypted)")).getAbsolutePath();
            processDirectoryRecursively(selectedInput.getAbsolutePath(), outputDirPath, false);
            
            // THÔNG BÁO THÀNH CÔNG
            JOptionPane.showMessageDialog(this, 
                "Thư mục đã được giải mã thành công!\n\nĐã lưu tại:\n" + outputDirPath, 
                "Hoàn thành", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // THÔNG BÁO LỖI NHẬP LIỆU
        JOptionPane.showMessageDialog(this, 
            "Lỗi: Khóa chia sẻ hoặc Số khung không hợp lệ.\nVui lòng kiểm tra lại.", 
            "Lỗi Nhập liệu", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // THÔNG BÁO LỖI CHUNG
        JOptionPane.showMessageDialog(this, 
            "Đã xảy ra lỗi trong quá trình giải mã:\n" + e.getMessage(), 
            "Lỗi", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_btnDecryptUser3ActionPerformed

   // Hàm đệ quy để xử lý mã hóa hoặc giải mã một thư mục và tất cả các thư mục con
private void processDirectoryRecursively(String inputDirPath, String outputDirPath, boolean isEncrypting) throws Exception {
    File inputDir = new File(inputDirPath);
    File outputDir = new File(outputDirPath);
    if (!outputDir.exists()) { outputDir.mkdirs(); }
    File[] filesList = inputDir.listFiles();
    if (filesList == null) return;

    for (File f : filesList) {
        // --- THAY ĐỔI Ở ĐÂY ---
        String outputFilePath = new File(outputDir, f.getName()).getAbsolutePath();
        if (isEncrypting) {
            if (f.isFile()) {
                // Không thêm đuôi .enc nữa
                processFileWithStreamCipher(f.getAbsolutePath(), outputFilePath); 
            } else if (f.isDirectory()) {
                processDirectoryRecursively(f.getAbsolutePath(), outputFilePath, true);
            }
        } else { // isDecrypting
            // Vì không có đuôi .enc, chúng ta sẽ giải mã mọi file
            if (f.isFile()) {
                processFileWithStreamCipher(f.getAbsolutePath(), outputFilePath);
            } else if (f.isDirectory()) {
                processDirectoryRecursively(f.getAbsolutePath(), outputFilePath, false);
            }
        }
    }
}
    
  // Hàm xử lý sự kiện cho nút "Mã hóa File/Thư mục" 
    private void btnEncryptUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptUser3ActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Chọn File hoặc Thư mục để Mã hóa");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

    if (fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        // Người dùng đã hủy, không cần thông báo gì
        return; 
    }
    
    File selectedInput = fileChooser.getSelectedFile();
    
    JFileChooser outputChooser = new JFileChooser();
    outputChooser.setDialogTitle("Chọn Thư mục để Lưu Kết quả Mã hóa");
    outputChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    
    if (outputChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
        // Người dùng đã hủy
        return; 
    }
    
    File selectedOutputLocation = outputChooser.getSelectedFile();

    try {
        if (selectedInput.isFile()) {
            // XỬ LÝ MÃ HÓA TỆP
            String outputFilePath = new File(selectedOutputLocation, selectedInput.getName()).getAbsolutePath();
            processFileWithStreamCipher(selectedInput.getAbsolutePath(), outputFilePath);
            
            // THÔNG BÁO THÀNH CÔNG
            JOptionPane.showMessageDialog(this, 
                "Tệp đã được mã hóa thành công (giữ nguyên tên)!\n\nĐã lưu tại:\n" + outputFilePath, 
                "Hoàn thành", 
                JOptionPane.INFORMATION_MESSAGE);

        } else if (selectedInput.isDirectory()) {
            // XỬ LÝ MÃ HÓA THƯ MỤC
            String outputDirPath = new File(selectedOutputLocation, selectedInput.getName() + " (Encrypted)").getAbsolutePath();
            processDirectoryRecursively(selectedInput.getAbsolutePath(), outputDirPath, true);
            
            // THÔNG BÁO THÀNH CÔNG
            JOptionPane.showMessageDialog(this, 
                "Thư mục đã được mã hóa thành công!\n\nĐã lưu tại:\n" + outputDirPath, 
                "Hoàn thành", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // THÔNG BÁO LỖI NHẬP LIỆU
        JOptionPane.showMessageDialog(this, 
            "Lỗi: Khóa chia sẻ hoặc Số khung không hợp lệ.\nVui lòng kiểm tra lại.", 
            "Lỗi Nhập liệu", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // THÔNG BÁO LỖI CHUNG
        JOptionPane.showMessageDialog(this, 
            "Đã xảy ra lỗi trong quá trình mã hóa:\n" + e.getMessage(), 
            "Lỗi", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_btnEncryptUser3ActionPerformed

    
    
    
    private void btnGenerateKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateKey1ActionPerformed
                                             
    Random random = new Random();
    int frameNumberInt = random.nextInt() & ((1 << 22) - 1);
    String frameNumberHex = String.format("%06X", frameNumberInt);

    // Hiển thị kết quả vào JTextField có tên là 'txtframe1'
    txtframe1.setText(frameNumberHex);
    
    // Xuất ra bảng thông báo xác nhận
    JOptionPane.showMessageDialog(this, 
        "Đã tạo số khung ngẫu nhiên mới: " + frameNumberHex, 
        "Thông báo", 
        JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnGenerateKey1ActionPerformed


    
    
     

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mahoa().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecryptUser1;
    private javax.swing.JButton btnDecryptUser2;
    private javax.swing.JButton btnDecryptUser3;
    private javax.swing.JButton btnEncryptUser1;
    private javax.swing.JButton btnEncryptUser2;
    private javax.swing.JButton btnEncryptUser3;
    private javax.swing.JButton btnGenerateKey;
    private javax.swing.JButton btnGenerateKey1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpKey;
    private javax.swing.JPanel jpKey1;
    private javax.swing.JLabel jpTieuDe;
    private javax.swing.JPanel jpUser1;
    private javax.swing.JPanel jpUser2;
    private javax.swing.JPanel jpUser3;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtKey1;
    private javax.swing.JTextField txtMessUser1;
    private javax.swing.JTextField txtMessUser2;
    private javax.swing.JTextField txtOutputUser1;
    private javax.swing.JTextField txtOutputUser2;
    private javax.swing.JTextField txtframe;
    private javax.swing.JTextField txtframe1;
    // End of variables declaration//GEN-END:variables

}